### ISSUE TITLE
조각 - [playbook] gradle 프로젝트 빌드하기

### ISSUE THREAD

**Issue by kwonslog** [kwonslog/how-to-use-ansible#2]
## playbook 파일을 작성하여 gradle 기반 프로젝트를 빌드하기.
- gradle 빌드를 위해 JDK를 미리 설치 필요함.
- 아래 파일 작성 할때 nano 편집기를 사용함.

### inventory 파일 작성
- test-inventory 파일을 작성한다.
```
[testing]
localhost
```
### playbook 파일 작성
- test-gradle-build.yml 파일을 작성한다.
```
- name: Gradle Build
  hosts: localhost
  vars:
    my_home: "/home/kwon"
    root_project_path: "/mnt/c/workspace/root-project"
	project_name: "app-server"

  tasks:
    - name: Clean specific project
      shell: "cd {{ root_project_path }} && ./gradlew :{{ project_name }}:clean"

    - name: Build JAR for specific project
      shell: "cd {{ root_project_path }} && ./gradlew :{{ project_name }}:bootJar"

    - name: Copy JAR file to destination
      copy:
        src: "{{ root_project_path }}/{{ project_name }}/build/libs/{{ project_name }}.jar"
        dest: "{{ my_home }}/{{ project_name }}.jar"
```
### playbook 실행
- 아래 명령어를 통해 실행 가능하다.
```
ansible-playbook -i test-inventory test-gradle-build.yml --connection=local
```

### 기억할 것
- `cd` 명령어 실행 후 이동한 경로는 유지 되지 않는다. 그래서 task 마다 cd 명령으로 이동했다.
- `--connection=local` 원래 SSH 연결을 통해 명령을 실행하는데 이 옵션을 사용하여 로컬에서 명령을 수행하도록 설정함.

### 기타
- `ansible-playbook -vvv` 옵션을 지정하면 진행 과정에 대한 상세 로그가 출력된다.
```
ansible-playbook -vvv -i test-inventory test-gradle-build.yml --connection=local
```
- `--connection=local` 옵션을 playbook 파일 안에 지정 하는 방법도 있다.
```
hosts: localhost
connection: local
```

**Comment by kwonslog** [comment]
### chdir 을 사용하여 명령어가 실행 되는 위치를 변경 할 수 있다.
```
- name: Gradle Build Local
  hosts: localhost
  connection: local
  vars:
    my_home: "/home/kwon"
    root_project_path: "/mnt/c/root-server"
	project_name: "app-server"

  tasks:
    - name: Clean & Build JAR
      shell: ./gradlew :app-server:clean && ./gradlew :app-server:bootJar
	  args:
	    chdir: "{{ root_project_path }}"

    - name: Copy JAR file to destination
      copy:
        src: "{{ root_project_path }}/{{ project_name }}/build/libs/{{ project_name }}.jar"
        dest: "{{ my_home }}/{{ project_name }}.jar"
```
