### ISSUE TITLE
조각 - [playbook] 원격 서버에 도커 및 도커 컴포즈 설치하기

### ISSUE THREAD

**Issue by kwonslog** [kwonslog/how-to-use-ansible#3]
## 도커 및 도커 컴포즈 설치하기
- 윈도우 환경 + Docker Desktop + 윈도우 우분투 앱을 설치한 상태.
- ubuntu 컨테이너를 실행하여 해당 컨테이너에 도커와 도커 컴포즈를 설치하는 것이 목표.

### 우분투 컨테이너 실행
- 다음 명령을 통해 컨테이너를 실행한다.
```
docker run -it -d --name local-ubuntu -p 8022:22 ubuntu
//로컬에서 컨테이너를 실행했기 때문에 SSH 접속을 하려면 -p 8022:22 포트 설정이 필요하다.
```
- 컨테이너가 실행중인지 확인한다.
```
docker ps
```
![image](https://github.com/kwonslog/how-to-use-ansible/assets/65941166/0bf8fd44-45ea-46be-9001-c9a53a0f5d14)

### SSH 설치
- 컨테이너에 터미널로 접속한다.
```
docker exec -it local-ubuntu /bin/sh
```
- SSH 서비스 설치
```
apt-get update
apt-get install -y openssh-server
```
- 패스워드 설정
```
passwd
//비밀번호를 root 로 설정함.
```
- sshd_config 파일 수정
```
nano /etc/ssh/sshd_config

//아래 2개 항목 주석해제
Port 22
PermitRootLogin yes
```
- ssh 서비스 상태 확인
```
service ssh status
```
![image](https://github.com/kwonslog/how-to-use-ansible/assets/65941166/8a525ced-6cdc-4749-be11-0876db970fc7)
- ssh 서비스 실행
```
service ssh start
```
![image](https://github.com/kwonslog/how-to-use-ansible/assets/65941166/053f344d-4868-4fe9-83ed-d584e882e4d9)
### 컨테이너 ip 확인
- cmd 창을 열어서 아래 명령을 실행하여 확인한다.
```
docker inspect -f "{{ .NetworkSettings.IPAddress }}" local-ubuntu
```
![image](https://github.com/kwonslog/how-to-use-ansible/assets/65941166/d27477a0-9a9f-41e3-ab94-42cde92bf955)

### 윈도우 우분투 앱에서 ssh key 생성
```
ssh-keygen
```
![image](https://github.com/kwonslog/how-to-use-ansible/assets/65941166/508d830d-1670-481c-8d5d-f0555702adb1)
이렇게 암호를 물어보면 enter 로 넘김.
```
ssh-copy-id -p8022 root@192.168.10.119
//로컬 컴퓨터의 ip 와 ubuntu 컨테이너와 연결되어 있는 포트를 사용
//그리고 비밀번호를 입력을 요구하면 ubuntu 컨테이너의 root 계정 비밀번호를 입력한다.
```
<img width="637" alt="image" src="https://github.com/kwonslog/how-to-use-ansible/assets/65941166/494f4680-5b1f-4306-98b6-b7d7db7cb877">

### 인벤토리 파일 작성
```
nano test-inv.ini

[local]
172.30.1.27:8022
```
### playbook 파일 작성
```
nano test-ssh.yml

- name: Install Docker using script
  hosts: local  
  #ssh 접속에 필요한 사용자 계정
  remote_user: root 
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
        state: present

    - name: Download Docker install script
      get_url:
        url: https://get.docker.com
        dest: /tmp/install_docker.sh
        mode: 0755

    - name: Run Docker install script
      command: /tmp/install_docker.sh
      args:
        creates: /usr/bin/docker

    - name: Add user to docker group
      user:
        name: root
        groups: docker
        append: yes

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add symbolic link for Docker Compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

ansible-playbook --syntax-check -i test-inv.ini test-ssh.yml
ansible-playbook -vvv -i test-inv.ini test-ssh.yml
```
- `remote_user: root` 는 ubuntu 컨테이너에 SSH 접속을 위한 사용자 계정을 입력해야 한다.
> ssh -p8022 root@192.168.10.119
> 이 명령으로 ssh 접속이 가능한지 체크해 본다.

### 참고자료
- https://try-it.tistory.com/49
