### ISSUE TITLE
조각 - [playbook] 로컬에서 빌드/압축, 원격 서버에서 압축해제 하기

### ISSUE THREAD

**Issue by kwonslog** [kwonslog/how-to-use-ansible#4]
### 처리과정
- ansible 을 사용하여 다음 과정을 실행하는 playbook 을 작성한다.

1. 로컬 컴퓨터에서 gradle 빌드를 실행
2. 빌드 결과물을 지정한 폴더로 복사
3. 해당 폴더를 tar 파일로 압축
4. 압축 파일을 원격 서버에 복사
5. 압축 파일의 압축을 해제

### 인벤토리 파일 작성
```
nano test-inv.ini

[local]
192.168.10.119:8022
```
### playbook 파일 작성
```
nano test-build.yml

- name: 빌드/압축/복사/압축해제 테스트
  hosts: local
  remote_user: root
  vars:
    my_home: "/home/kwon"
    test_arch_dir: "/home/kwon/testdir"
    root_project_path: "/mnt/c/server"
    project_name: "app-server"

  tasks:
    - name: 1.로컬 컴퓨터에서 gradle 빌드를 실행
      shell: "./gradlew :{{ project_name }}:clean && ./gradlew :{{ project_name }}:bootJar"
      args:
        chdir: "{{ root_project_path }}"
      delegate_to: localhost

    - name: 2.빌드 결과물을 지정한 폴더로 복사
      copy:
        src: "{{ root_project_path }}/{{ project_name }}/build/libs/{{ project_name }}.jar"
        dest: "{{ test_arch_dir }}/{{ project_name }}.jar"
      delegate_to: localhost

    - name: 3.해당 폴더를 tar 파일로 압축
      archive:
        path: "{{ test_arch_dir }}"
        dest: "{{ my_home }}/archive.tar.gz"
        format: gz
      delegate_to: localhost

    - name: 4.압축 파일을 원격 서버에 복사
      copy:
        src: "{{ my_home }}/archive.tar.gz"
        dest: "/root/archive.tar.gz"

    - name: 5.압축 파일의 압축을 해제
      unarchive:
        src: "/root/archive.tar.gz"
        dest: "/root"
        remote_src: yes
    
ansible-playbook --syntax-check -i test-inv.ini test-build.yml
ansible-playbook -v -i test-inv.ini test-build.yml
```
- `delegate_to: localhost`은 로컬 컴퓨터에서 명령을 실행한다. 
- 그래서 3번까지의 과정은 로컬 컴퓨터에 있는 빌드 결과물을 압축한다.
- 그리고 4번부터는 로컬 컴퓨터에 있는 결과물을 원격 호스트에 복사하고 압축을 해제 한다.
